from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
import io
from datetime import datetime

def generate_analysis_pdf(data: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"],
        fontSize=24, textColor=colors.HexColor("#7c6ef7"),
        alignment=TA_CENTER, spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"],
        fontSize=11, textColor=colors.grey,
        alignment=TA_CENTER, spaceAfter=20
    )

    elements.append(Paragraph("📈 Deep Market Inspection", title_style))
    elements.append(Paragraph(f"Analysis Report for {data['ticker']}", subtitle_style))
    elements.append(Spacer(1, 10))

    summary_color = {
        "BULLISH": colors.HexColor("#16a34a"),
        "BEARISH": colors.HexColor("#dc2626"),
        "NEUTRAL": colors.HexColor("#d97706"),
    }.get(data["summary"], colors.grey)

    info_data = [
        ["Ticker", data["ticker"]],
        ["Latest Price", f"${data['latest_price']}"],
        ["Period", data["period"]],
        ["Overall Signal", data["summary"]],
        ["Report Generated", datetime.now().strftime("%B %d, %Y at %I:%M %p")],
    ]

    info_table = Table(info_data, colWidths=[5*cm, 9*cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#f3f0ff")),
        ("TEXTCOLOR", (0,0), (0,-1), colors.HexColor("#7c6ef7")),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME", (1,0), (1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 11),
        ("BOTTOMPADDING", (0,0), (-1,-1), 10),
        ("TOPPADDING", (0,0), (-1,-1), 10),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#e5e5e5")),
        ("TEXTCOLOR", (1,3), (1,3), summary_color),
        ("FONTNAME", (1,3), (1,3), "Helvetica-Bold"),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 24))

    elements.append(Paragraph("Indicator Signals", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    signal_data = [["Indicator", "Signal", "Reason"]]
    for s in data["signals"]:
        signal_data.append([s["indicator"], s["signal"], s["reason"]])

    signal_table = Table(signal_data, colWidths=[3.5*cm, 2.5*cm, 8*cm])
    table_style = [
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#7c6ef7")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#e5e5e5")),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
    ]

    for i, s in enumerate(data["signals"], start=1):
        color = {
            "BUY": colors.HexColor("#16a34a"),
            "SELL": colors.HexColor("#dc2626"),
            "NEUTRAL": colors.HexColor("#d97706"),
        }.get(s["signal"], colors.black)
        table_style.append(("TEXTCOLOR", (1,i), (1,i), color))
        table_style.append(("FONTNAME", (1,i), (1,i), "Helvetica-Bold"))

    signal_table.setStyle(TableStyle(table_style))
    elements.append(signal_table)
    elements.append(Spacer(1, 30))

    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontSize=8, textColor=colors.grey, alignment=TA_CENTER
    )
    elements.append(Paragraph(
        "Generated by Deep Market Inspection — This report is for informational purposes only and is not financial advice.",
        footer_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer